CREATE TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                      UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id
    BIGINT
    GENERATED
    BY
    DEFAULT AS
    IDENTITY
    PRIMARY
    KEY,
    title
    VARCHAR
(
    120
) NOT NULL,
    annotation TEXT NOT NULL,
    description TEXT NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories
(
    id
) ON DELETE RESTRICT,
    initiator_id BIGINT NOT NULL REFERENCES users
(
    id
)
  ON DELETE CASCADE,
    event_date TIMESTAMP NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_on TIMESTAMP,
    location_lat FLOAT NOT NULL,
    location_lon FLOAT NOT NULL,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
    state VARCHAR
(
    20
) NOT NULL -- ,
-- CONSTRAINT fk_events_initiator_id FOREIGN KEY (initiator_id) REFERENCES users (id)
    );
