services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://stats-db-postgres:5432/explore_with_me"
      SPRING_DATASOURCE_USERNAME: "explore-with-me"
      SPRING_DATASOURCE_PASSWORD: "explore-with-me"

  stats-db:
    image: postgres:16.1
    container_name: stats-db-postgres
    ports:
      - "7432:5432"
      - "5432:5432"
    environment:
      POSTGRES_USER: "ewm-stats"
      POSTGRES_PASSWORD: "ewm-stats"
      POSTGRES_DB: "ewm"
      POSTGRES_INITDB_ARGS: "--auth=scram-sha-256 --username=ewm-stats"
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: main-service
    image: explore-with-me-main-service
    container_name: explore-with-me-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      STATS-CLIENT_SERVER-URL: "http://stats-server:9090"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://ewm-db-postgres:5432/ewm"
      SPRING_DATASOURCE_USERNAME: "ewm-stats"
      SPRING_DATASOURCE_PASSWORD: "ewm-stats"

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db-postgres
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: "ewm-stats"
      POSTGRES_PASSWORD: "ewm-stats"
      POSTGRES_DB: "ewm"
      POSTGRES_INITDB_ARGS: "--auth=scram-sha-256 --username=ewm-stats"
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
