CREATE TABLE queries_stats
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(255) NOT NULL,
    uri       TEXT         NOT NULL,
    ip        VARCHAR(45)  NOT NULL,
    timestamp TIMESTAMP    NOT NULL
);

CREATE INDEX idx_queries_stats_app ON queries_stats (app);
CREATE INDEX idx_queries_stats_app ON queries_stats (timestamp);
